### 1. 다음 코드의 실행 결과를 작성하세요.(민아) 
```java
class Main {
    public static void main(String[] args) {
        System.out.println(1) ;
        System.out.println(2);
        try {
            System.out.println(3);
            System.out.println(0/0);
            System.out.println(4) ;
        } catch (ArithmeticException ae) {
            System.out.println(5);
        }
        System.out.println (6);
    }
}
```

### 2. 다음에서 설명하는 메서드가 무엇인지 작성하세요.(민아)
a. 예외발생 당시의 호출스택(Call Stack)에 있었던 메서드의 정보와 예외 메시지를 화면에 출력한다.
<br>
b. 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.

### 3. 다음 코드의 실행 결과를 작성하세요.(민아)
```java
class Main {
    public static void main(String[] args) {
        int iVal = 100;
        String strVal = String. valueOf (iVal);

        double dVal = 200.0;
        String strVal2 = dVal + "";

        double sum = Integer.parseInt("+"+strVal)
        + Double.parseDouble(strVal2);

        double sum2 = Integer.valueOf(strVal) + Double.valueOf(strVal2);
        System.out.println(String.join("",strVal,"+", strVal2, "=")+sum);
        System.out.println(strVal+"+"+strVal2+"="+sum2) ;
    }
}
```

### 4. 예외처리의 정의와 목적을 설명하세요.(성훈)

<br>

### 5. 다음 코드의 실행 결과를 설명하세요.(성훈)

```java
public class Main {
    public static void main(String[] args) {
        try {
            method1();
        } catch (Exception e) {
            System.out.println("main메서드에서 예외가처리되었습니다.");
            e.printStackTrace();
        }
    }
    static void method1() throws Exception {
throw new Exception();
    }
}
```

<br>

### 6. 다음 코드의 실행 결과를 설명하세요.(성훈)

```java
public class Main {
    public static void main(String[] args) {
        Main.method1();
        System.out.println ("method1()의 수행을 마치고 main메서드로 돌아왔습니다.");
    }
    static void method1() {
        try {
            System.out.println ("method1()이 호출되었습니다. ") ;
            return;
        } catch (Exception e) {
            e.printStackTrace() ;
        } finally {
            System. out.println ("method1()의 finally블럭이 실행되었습니다.") ;
        }
    }
}
```

<br>