### 1. 다음 코드의 실행 결과를 작성하세요.(민아) 
```java
class Main {
    public static void main(String[] args) {
        System.out.println(1) ;
        System.out.println(2);
        try {
            System.out.println(3);
            System.out.println(0/0);
            System.out.println(4) ;
        } catch (ArithmeticException ae) {
            System.out.println(5);
        }
        System.out.println (6);
    }
}
```

### 2. 다음에서 설명하는 메서드가 무엇인지 작성하세요.(민아)
a. 예외발생 당시의 호출스택(Call Stack)에 있었던 메서드의 정보와 예외 메시지를 화면에 출력한다.
<br>
b. 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.

### 3. 다음 코드의 실행 결과를 작성하세요.(민아)
```java
class Main {
    public static void main(String[] args) {
        int iVal = 100;
        String strVal = String. valueOf (iVal);

        double dVal = 200.0;
        String strVal2 = dVal + "";

        double sum = Integer.parseInt("+"+strVal)
        + Double.parseDouble(strVal2);

        double sum2 = Integer.valueOf(strVal) + Double.valueOf(strVal2);
        System.out.println(String.join("",strVal,"+", strVal2, "=")+sum);
        System.out.println(strVal+"+"+strVal2+"="+sum2) ;
    }
}
```