### 1. 다음 코드의 실행 결과를 작성하세요.(민아) 
```java
class Main {
    public static void main(String[] args) {
        System.out.println(1) ;
        System.out.println(2);
        try {
            System.out.println(3);
            System.out.println(0/0);
            System.out.println(4) ;
        } catch (ArithmeticException ae) {
            System.out.println(5);
        }
        System.out.println (6);
    }
}
```

<br></br>

### 2. 다음에서 설명하는 메서드가 무엇인지 작성하세요.(민아)
a. 예외발생 당시의 호출스택(Call Stack)에 있었던 메서드의 정보와 예외 메시지를 화면에 출력한다.
<br>
b. 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.

<br></br>

### 3. 다음 코드의 실행 결과를 작성하세요.(민아)
```java
class Main {
    public static void main(String[] args) {
        int iVal = 100;
        String strVal = String. valueOf (iVal);

        double dVal = 200.0;
        String strVal2 = dVal + "";

        double sum = Integer.parseInt("+"+strVal)
        + Double.parseDouble(strVal2);

        double sum2 = Integer.valueOf(strVal) + Double.valueOf(strVal2);
        System.out.println(String.join("",strVal,"+", strVal2, "=")+sum);
        System.out.println(strVal+"+"+strVal2+"="+sum2) ;
    }
}
```

<br></br>

### 4. 예외처리의 정의와 목적을 설명하세요.(성훈)

<br></br>

### 5. 다음 코드의 실행 결과를 설명하세요.(성훈)

```java
public class Main {
    public static void main(String[] args) {
        try {
            method1();
        } catch (Exception e) {
            System.out.println("main메서드에서 예외가처리되었습니다.");
            e.printStackTrace();
        }
    }
    static void method1() throws Exception {
throw new Exception();
    }
}
```

<br></br>

### 6. 다음 코드의 실행 결과를 설명하세요.(성훈)

```java
public class Main {
    public static void main(String[] args) {
        Main.method1();
        System.out.println ("method1()의 수행을 마치고 main메서드로 돌아왔습니다.");
    }
    static void method1() {
        try {
            System.out.println ("method1()이 호출되었습니다. ") ;
            return;
        } catch (Exception e) {
            e.printStackTrace() ;
        } finally {
            System. out.println ("method1()의 finally블럭이 실행되었습니다.") ;
        }
    }
}
```

<br></br>

### 7. try-catch 문의 변형으로, 자동으로 자원을 반환할 때 사용하는 문은 무엇인가요? 그리고 해당 문을 사용하면 자동으로 호출되는 메서드와, 자동으로 호출되기 위해서는 클래스가 어떤 인터페이스를 구현해야 하는지 설명해주세요.(선민)

<br></br>

### 8. String 클래스의 불변성에 대해 설명하고, 문자열 결합이 빈번할 때 String 클래스 대신 어떤 클래스를 사용하면 좋은지, 해당 클래스들은 어떤 특징을 갖는지 설명해주세요.(선민)

<br></br>

### 9. 사용자로부터 1 ~ 100 사이의 값을 입력받는 코드를 작성하세요. 만약 값이 해당 범위를 넘어설 경우 예외를 발생시키고, 예외 인스턴스를 통해 `1 ~ 100 사이의 값만 입력해주세요`라는 에러 메시지를 출력할 수 있도록 해주세요.(선민)

<br></br>

<br>

### 10. 아래의 코드에서 어떠한 예외도 던져지지 않은 경우 실행되는 코드는 무엇인지 설명하시오.(지영)

```java

try{ 
    // (1)
} catch(Exception1 e1){ 
    // (2) 
} catch(Exception2 e2){
    // (3) 
} finally{ 
    //(4) 
}
// (5)

```

<br></br>

### 11. 예외처리문에서 catch 블록 없이 try-finally 블록만 가진 코드가 의도하는 것은 무엇인지 설명하고 사용 예시를 들어주세요.(지영)

```java
try{
    ...
} finally{
    ...
}

```

<br></br>

### 12. 다음 코드의 출력 결과를 보고 equals() 메서드의 특징에 대해 설명하시오.(지영)

```java
public class Problem12{
    public static void main(String[] args) {
        String str1 = "abc";
        String str2 = new String("abc");
        String str3 = new String("abc");

        System.out.println("==연산자");
        System.out.println(str1 == "abc");
        System.out.println(str2 == "abc");

        System.out.println("equals 메서드");
        System.out.println(str1.equals("abc"));
        System.out.println(str2.equals("abc"));
        System.out.println(str2.equals(str3));
        
        System.out.println(str2.equals("ABC"));
    }
}
```

<br></br>


### 13. 예외 되던지기가 무엇인지 설명하시오.(기훈)

<br></br>

### 14. java.lang 패키지의 특징과 자주사용되는 클래스 2가지를 설명하시오.(기훈)

<br></br>

### 15. String클래스의 특징을 설명하시오. (기훈)

<br></br>

### 16. try-catch-finally 블록에 대한 설명 중 틀린 것은 무엇입니까? (현수)
1. try {} 블록에는 예외가 발생할 수 있는 코드를 작성한다.
2. catch {}블록은 try {} 블록에서 발생한 예외를 처리하는 블록이다.
3. try {} 블록에서 return 문을 사용하면 finally {} 블록은 실행되지 않는다.
4. catch {} 블록은 예외의 종류별로 여러 개를 작성할 수 있다.

<br></br>

### 17. throws에 대한 설명으로 틀린 것은 무엇입니까? (현수)
1. 생성자나 메소드의 선언 끝 부분에 사용되어 내부에서 발생된 예외를 떠넘긴다.
2. throws 뒤에는 떠넘겨야 할 예외를 쉼표(,)로 구분해서 기술한다.
3. 모든 예외를 더넘기기 위해 간단하게 throws Exception으로 작성할 수 있다.
4. 새로운 예외를 발생시키기 위해 사용된다.

<br></br>

### 18. 메소드가 다음과 같이 선언되어 있습니다. 잘못된 예외 처리를 선택하세요. (현수)
```java
public void method1() throws NumberFormatException, ClassNotFoundException { ... }
```
1. try {method1():} catch (Exception e) {}
2. void method2() throws Exception {methodl(); }
3. try { method1(); }<br>
catch (Exception e) {}<br>
catch (ClassNotFoundException e) {}
4. try (method1(); }<br>
catch (ClassNotFoundException e) {}<br>
catch (NumberFormatException e) {}